### ISSUE TITLE
Two more dependencies needed

### ISSUE THREAD

**Issue by rmnguleria** [ExpediaInceCommercePlatform/cyclotron#1]
Hi Fellow Expedian , 
For me after installing gulp(3.8) globally it needed two more steps .

1. npm install coffee-script
2. npm install gulp-concat

**Comment by baumandm** [comment]
Both of these dependencies are included in the package.json, [here](https://github.com/ExpediaInceCommercePlatform/cyclotron/blob/master/cyclotron-site/package.json#L24) and [here](https://github.com/ExpediaInceCommercePlatform/cyclotron/blob/master/cyclotron-site/package.json#L30).  Did you run `npm install` before running gulp?

**Comment by rmnguleria** [comment]
Oh yeah . My mistake .
