### ISSUE TITLE
Cannot connect to cyclotron-svc

### ISSUE THREAD

**Issue by neilgask** [ExpediaInceCommercePlatform/cyclotron#13]
Hiya,

I'm getting this on a fresh install on a new Centos 7 VM (Linode)

I think it's an IP6 thing - 

netstat -nl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp6       0      0 :::8077                 :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN

It's only listening on ip6, and ping6 localhost doesn't resolve. I can go

lynx http://[::1]:8077 

and get the Cyclotron doc page, and the cyclotron-svc stdout lists the connection. But if I put that URL into cyclotron-site/_public/js/conf/configService.js I still get the error. The cyclotron-svc stdout doesn't list any connection when cyclotron-site fails to connect so I don't think it's an auth thing.

Do you have any advice? I can't see where to tell svc where to bind, and I read that disabling ipv6 on Centos 7 causes issues.

Many thanks
Neil

**Comment by baumandm** [comment]
Hi @neilgask, I haven't done any testing with IPv6 yet, so I'm not sure what the best course of action is.  The easiest approach would be to use the IPv6 IP in the configService.js, which you did, but I'm not sure why that didn't work.  The fact that the API docs were being served definitely means it is listening on the IP address.  Did you dig into the network requests tab of the browser's dev tools to see if there's any more information there?

The other options would be forcing it to bind to IPv4.  I think you can force this by changing the last lines of app.js to include an IP:

    app.listen(port, '0.0.0.0', function(){
        console.log('Cyclotron running on port %d', port);
    });

I don't currently have an IPv6 box so I haven't tested this option yet.  I'll try to find some time to do my own investigation into this and the IPv6 support.  Let me know if you have any luck.

**Comment by neilgask** [comment]
Thanks! The app.js change got it listening on ip4. But also it was a misunderstanding on my part. I thought that it was the cyclotron-site that connected to cyclotron-svc on localhost:8087, but I understand now it's my local browser that connects to server:8077 as well as :8080. So by having the svc listening on ip4 0.0.0.0 and changing cyclotron-site/_public/js/conf/configService.js with the server's IP has got everything working. Many thanks for your help I look forward to playing with this :)
