### ISSUE TITLE
Recommended OS or guidance on API

### ISSUE THREAD

**Issue by carrotking** [ExpediaInceCommercePlatform/cyclotron#27]
I'm using Ubuntu 14.04 LTS and followed installation instructions for cyclotron. Many things are working, but not everything.  What build of what distro is known to work with cyclotron?

I can load the api pages and dashboard admin interface, create dashboards, and view them.  However I cannot successfully test any of the API.  A simple one such as Get /dashboards returns 404 "Cannot GET /api/dashboards?session=api_key

Should I try installling on a different version of linux?  Where do I get/set the api_key anyway?

**Comment by baumandm** [comment]
Hi @carrotking.  I'm not aware of any specific OS limitations, and to my knowledge it should work fine on Ubuntu.  I think this is just an issue with the Swagger UI, as creating/viewing dashboards works fine.  

The "basePath" property in the `swagger.json` is not correctly configured for standalone use, causing the 404 errors.  It's set to `"/api"`, but that requires you to use Nginx or another server to proxy the service.  If you change this value to `"/"` and reload the Swagger UI, it should start working.  The Swagger UI has a field for API Key, but this isn't needed so you can leave it blank.
