### ISSUE TITLE
Supporting Right to Left Languages

### ISSUE THREAD

**Issue by hatem1975** [ExpediaInceCommercePlatform/cyclotron#28]
Dear's
did any one try the platform in Right to Left Languages ?

**Comment by baumandm** [comment]
Hi @hatem1975, I haven't heard any reports of users using RTL languages with Cyclotron before.  There hasn't been any specific RTL functionality added, so it's likely that this is an area that could use some improvement.

If you try it and find any issues, pull requests in this area would be most welcome!
