### ISSUE TITLE
Keep code and configs in Source/Version control system?

### ISSUE THREAD

**Issue by hmanchev** [ExpediaInceCommercePlatform/cyclotron#29]
Hello team,

I am working on creating several dashboards using Cyclotron with great success! 
Now it is time to store my code/configurations, so I tried to find if there is a way to "build" the tool and to get files with my datasources and/or the configurations for the pages, widgets, etc but without luck.

So could you please guide me with the best approach to put all my work (code) for the dashboards (datasources, configurations) to some version control system (like GitHub)?
 
Thank you in advance and regards
Hristo

**Comment by baumandm** [comment]
Hi @hmanchev, glad to hear you're having success.  Cyclotron stores all the dashboard configuration in MongoDB and doesn't have any direct integration with version control, so there's not a built-in way to do what you are asking.

However, you can use the REST API to upload/download JSON files for each dashboard.  So my suggestion is to export and store the JSON files for your dashboards in your version control system, then write a script that can loop through all the files, `POST`ing them to the REST API using curl or similar.  You could automate this with a CI tool to automatically deploy dashboards after any change.

The downside to this approach is that if you edit the dashboards directly in the UI, you'll have to remember to manually sync the changes back into version control.  You might find the Clone Dashboard feature useful if you're working on a v2 of a dashboard, so your changes don't accidentally get overridden.

Hope this helps!

**Comment by hmanchev** [comment]
Hello @baumandm, thank you for your fast and detailed response!
I think this will help us. 

Best regards,
Hristo
