### ISSUE TITLE
WIKI - Tutorial

### ISSUE THREAD

**Issue by panbhatt** [ExpediaInceCommercePlatform/cyclotron#7]
Hi Team,
   This seems to be an excellent project however it lacks a lot on tutorial front. I set it up and navigate through the swagger/UI of the project. It would be great if we can have an example how to set it up for a normal usage. 
Ex-> how to use JSON to populate widgets on a SALES dashboard. 
I am ready to contribute in the tutorial part, if required and being provided with little help here n there. Let me know your viewpoints, it would be extremely useful for all the open source projects. Cheers.

**Comment by Longlepham** [comment]
Hey @panbhatt -

Our team has recognized that documentation is a key improvement opportunity for Cyclotron. We are currently in the process of evaluating the organization of our core product documentation including Tutorials and will send out communications once this is ready.

If you haven't already, please check out the Cyclotron [Quick Start Guide](http://localhost:777/help?q=Quick%20Start) for more information into building awesome dashboards!

**Comment by panbhatt** [comment]
Thanks. Got some great help in the help section. Let me know, if i can contribute towards documentation in any way. Closing this now.
