### ISSUE TITLE
Time Zone Capabilities for Clock Widget

### ISSUE THREAD

**Issue by jnicoara11** [ExpediaInceCommercePlatform/cyclotron#9]
Is there anyway we can add a time zone capability for the clock widget?

**Comment by Longlepham** [comment]
Hey @jnicoara11 -

It is indeed possible, surprisingly enough (in retrospect) having the ability to select time zones was not in our initial set of requirements for the clock widget.

I have logged this feature request into our backlog but we'd be more than happy to merge in a contribution.

Please continue to share your feature requests and feedback with us!

**Comment by jnicoara11** [comment]
Awesome! I can't wait for that functionality. When do you think that will be able to be done?

**Comment by Longlepham** [comment]
We are initially targeting around the beginning of the new year to deliver this feature. If this estimate changes, I will reach out to you directly for updates!

**Comment by jnicoara11** [comment]
Thank you!

**Comment by Longlepham** [comment]
Hey @jnicoara11 -

I'm excited to let you know that we have enabled the ability to select specific time zones for the clock widget in our latest Cyclotron release ([1.45.0](https://github.com/ExpediaInceCommercePlatform/cyclotron/releases))!

Please let us know if you have any questions or ideas on additional feature enhancements!

Thanks,
Long
